# -*- coding: utf-8 -*-
"""04-visualizacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XlZV4YK0MLpFQV1RQEiIl_ZNFsJCY-Pq

# Pasos a seguir 📚

## ☝️ Primero:

### *Revisa el Notebook de gráficos simples y crea un gráfico que:*

*   Utilice datos de empleo de estados unidos (data.us_employment()).
*   Sea un gráfico de línea.
*   En el eje $x$ visualices los meses.
*   En el eje $y$ visualices el cambio en el sector no agricola (nonfram_change).
*   Que la línea sea de color negro.
*   Que el gráfico sea de un ancho de 650px.
*   Que el gráfico tenga un título descriptivo.

 Bonus: El mismo gráfico pero en "área", es decir, que sea un gráfico de área.

¿Qué enfatiza más el gráfico de área, a comparación con el de línea?

#**Creación de un gráfico de línea**
"""

import altair as alt
import seaborn as sns

from vega_datasets import data

desafio = data.us_employment()
desafio.head()

alt.Chart(desafio).mark_line(color ='#0C0000').encode(
    x = alt.X("month:T",title= " "),
    y = alt.Y("nonfarm_change") 
).properties(
    title = "Empleo en Estados Unidos y el cambio en el sector no agrícola.",
    width = 650
)

"""#**Creación de un gráfico de área**"""

alt.Chart(desafio).mark_area(color ='#0C0000').encode(
    x = alt.X("month:T",title= " "),
    y = alt.Y("nonfarm_change") 
).properties(
    title = "Empleo en Estados Unidos y el cambio en el sector no agrícola.",
    width = 650
)

"""# **¿Qué enfatiza más el gráfico de área, a comparación con el de línea?**

Los cambios que hubo en los empleos de Estados Unidos, donde pareciera que en el 2009 no hubo tantos como en los otros años dentro del sector no agricola.

## ☝️ Segundo:

### *Revisa el Notebook de gráficos complejos y crea un gráfico de barras que:*

 * Utilice el conjunto de datos de pingüinos.
 * Los marcadores sean barras.
 * En el eje $x$ se visualiza la longitud promedio de las aletas de cada especie de pingüino.
 * En el eje $y$ se visualiza la especie del pingüino.
 Cada barra tiene también una etiqueta con la especie del pingüino.
"""

import altair as alt
import seaborn as sns

pinguinos = sns.utils.load_dataset("penguins")

pinguinos.head()

pinguinosBarras = alt.Chart(pinguinos).mark_bar(color = "#D358F7").encode(   
  x = alt.X("mean(flipper_length_mm):Q",title="Longitud de aleta de pingüino en mm"),
  y = alt.Y("species", title="Especies")
).properties(
    title = "Promedio de las aletas de cada especie de pingüino."
)

pinguinosTexto = alt.Chart(pinguinos).mark_text(size = 16).encode(
    x = alt.X("mean(flipper_length_mm):Q"),
    y = alt.Y("species"),
    text = alt.Text("species:N")
)

aletasPinguinos = pinguinosBarras + pinguinosTexto

aletasPinguinos.properties(
    width = 650,
    height = 200
)

"""## ☝️ Tercero:

### *Revisa el Notebook de compartir gráficos y exporta cualquiera de los gráficos que hayas creado:*

* Usa los colores y formato al que consideres más adecuado.
"""

aletasPinguinos.save("promedioAletasPinguinos.html")