# -*- coding: utf-8 -*-
"""Copia de 09-Compartir-tus-gráficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ds-64e-MwzE75n1igWQnvtpU28elWjf

<p align="center">
<img src="http://codeandomexico.org/resources/img/codeandomexico.png" width="500" alt="Codeando México"><br>
<a href="http://www.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/website-CodeandoMexico-00D88E.svg"></a>
<a href="http://slack.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/slack-CodeandoMexico-EC0E4F.svg"></a>
</p>
<!-- __ -->

# Curso de Datos Abiertos y Hacking Cívico

Este curso tiene como objetivo habilitar las capacidades de la ciudadanía y los servidores públicos en el uso y generación de datos abiertos para el bien común. Puedes encontrar más información [aquí](https://github.com/CodeandoMexico/hacking-civico).

# Compartir tus graficos
"""

import altair as alt
import seaborn as sns

pinguinos = sns.utils.load_dataset("penguins")

pinguinos.head()

dispersion_base = alt.Chart(pinguinos).mark_circle(fillOpacity = 0.50).encode(
    x = alt.X("bill_length_mm:Q", title = "Largo del pico (mm)"),
    y = alt.Y("bill_depth_mm:Q", title = "Profundidad del pico (mm)"),
    color = alt.Color("species:N")
)

dispersion_texto = alt.Chart(pinguinos).mark_text(size = 16).encode(
    x = alt.X("mean(bill_length_mm):Q", ),
    y = alt.Y("mean(bill_depth_mm):Q"),
    text = alt.Text("species:N")
)

grafico_compuesto = dispersion_base + dispersion_texto

grafico_compuesto.properties(
    width = 600,
    height= 200
)

"""# `.save()`"""

grafico_compuesto.save("mi_grafico.html")

